export const AUTH_TOKEN_KEY = 'AUTH_TOKEN_KEY';
export const DEVICE_TOKEN_KEY = 'fcmToken';
export const TOKEN_PAYLOAD_KEY = 'authorization';
export const DEVICE_PAYLOAD_KEY = 'Device-Token';
export const PUBLIC_REQUEST_KEY = 'public-request';

export const professions = [
  'Accountant',
  'Actor/Actress',
  'Architect',
  'Artist',
  'Baker',
  'Banker',
  'Barista',
  'Biologist',
  'Blogger',
  'Carpenter',
  'Chef',
  'Civil Engineer',
  'Consultant',
  'Dancer',
  'Dentist',
  'Designer',
  'Doctor',
  'Economist',
  'Electrician',
  'Engineer',
  'Entrepreneur',
  'Event Planner',
  'Farmer',
  'Fashion Designer',
  'Firefighter',
  'Fitness Trainer',
  'Florist',
  'Graphic Designer',
  'Hairstylist',
  'Interior Designer',
  'Journalist',
  'Lawyer',
  'Librarian',
  'Marketing Manager',
  'Musician',
  'Nurse',
  'Pharmacist',
  'Photographer',
  'Pilot',
  'Police Officer',
  'Professor',
  'Programmer',
  'Psychologist',
  'Real Estate Agent',
  'Scientist',
  'Software Developer',
  'Surgeon',
  'Teacher',
  'Veterinarian',
  'Writer'
];

export const religions = [
  'Hindu',
  'Christian',
  'Muslim',
  'Buddhist',
  'Sikh',
  'Jain',
  'Other',
];

export const interests = [
  'Hiking',
  'Cooking',
  'Traveling',
  'Reading',
  'Swimming',
  'Yoga',
  'Watching movies',
  'Playing sports',
  'Photography',
  'Volunteering',
  'Painting',
  'Dancing',
  'Meditation',
  'Playing video games',
  'Writing',
  'Gardening',
  'Cycling',
  'Collecting art',
  'Playing board games',
  'Playing musical instruments',
  'Singing',
  'Fishing',
  'Knitting',
  'Skiing',
  'Fashion designing',
  'Horse riding',
  'Learning new languages',
  'Solving puzzles',
  'Attending live concerts',
  'Interior designing',
  'Bird watching',
  'Camping',
  'Pottery',
  'Baking',
  'Rock climbing',
  'Sailing',
  'Surfing',
  'Archery',
  'Acting',
  'Calligraphy',
  'Fashion blogging',
  'Robotics',
  'Scuba diving',
  'Woodworking',
  'Magic tricks',
  'Astronomy',
  'Comic book collecting',
  'Beekeeping',
  'Ghost hunting'
];


export const nonInterests = [
  'Smoking',
  'Excessive drinking',
  'Partying',
  'Gambling',
  'Hunting',
  'Watching sports',
  'Clubbing',
  'Reality TV',
  'Fast food',
  'Loud music',
  'Drugs',
  'Violent movies',
  'Heavy metal music',
  'Speed dating',
  'Laziness',
  'Materialism',
  'Feminism',
  'Being indoors all the time',
  'Constant arguing',
  'Overly competitive activities',
  'Overuse of social media',
  'Gossiping',
  'Selfishness',
  'Negativity',
  'Unhealthy eating habits',
  'Irresponsibility',
  'Narcissism',
  'Intolerance',
  'Arrogance',
  'Ignorance',
  'Pessimism',
  'Procrastination',
  'Rudeness',
  'Cruelty',
  'Dishonesty',
  'Self-centeredness',
  'Close-mindedness',
  'Recklessness',
  'Indecisiveness',
  'Inflexibility',
  'Overspending',
  'Aggressiveness',
  'Oversleeping',
  'Wastefulness',
  'Self-doubt',
  'Neglectfulness',
  'Impulsiveness'
];
;
