export const AUTH_TOKEN_KEY = 'AUTH_TOKEN_KEY';
export const DEVICE_TOKEN_KEY = 'fcmToken';
export const TOKEN_PAYLOAD_KEY = 'authorization';
export const DEVICE_PAYLOAD_KEY = 'Device-Token';
export const PUBLIC_REQUEST_KEY = 'public-request';

export const professions = [
  'Accountant',
  'Actor/Actress',
  'Architect',
  'Artist',
  'Baker',
  'Banker',
  'Barista',
  'Biologist',
  'Blogger',
  'Carpenter',
  'Chef',
  'Civil Engineer',
  'Consultant',
  'Dancer',
  'Dentist',
  'Designer',
  'Doctor',
  'Economist',
  'Electrician',
  'Engineer',
  'Entrepreneur',
  'Event Planner',
  'Farmer',
  'Fashion Designer',
  'Firefighter',
  'Fitness Trainer',
  'Florist',
  'Graphic Designer',
  'Hairstylist',
  'Interior Designer',
  'Journalist',
  'Lawyer',
  'Librarian',
  'Marketing Manager',
  'Musician',
  'Nurse',
  'Pharmacist',
  'Photographer',
  'Pilot',
  'Police Officer',
  'Professor',
  'Programmer',
  'Psychologist',
  'Real Estate Agent',
  'Scientist',
  'Software Developer',
  'Surgeon',
  'Teacher',
  'Veterinarian',
  'Writer'
];

export const religions = [
    'Hindu',
    'Christian',
    'Muslim',
    'Buddhist',
    'Sikh',
    'Jain',
    'Other',
];